### ISSUE TITLE
Bump Pip version to 2.1

### ISSUE THREAD

**Issue by JonahKr** [rhasspy/rhasspy-nlu#13]
there already was a issue on the community forum regarding this.
Maybe this can be automated with a github action?

**Comment by koenvervloesem** [comment]
Yes, we're dealing with this repository by repository. I fixed this now in https://github.com/rhasspy/rhasspy-nlu/commit/b740f2b671285003ad49beb76356c67e01d8b4d6.

@synesthesiam can you upload the 0.2.1 release to PyPI manually this time?

**Comment by synesthesiam** [comment]
Hoping this issue has been resolved by now. The versions are all over the place now with the addition of Raven and some changes to rhasspy-hermes...
