### ISSUE TITLE
rhasspy-nlu 0.1.4.1 networkx 2.4 which is incompatible.

### ISSUE THREAD

**Issue by gericho** [rhasspy/rhasspy-nlu#5]
ERROR: rhasspy-nlu 0.1.4.1 has requirement networkx==2.3, but you'll have networkx 2.4 which is incompatible.

how to solve the issue?
thanks

**Comment by koenvervloesem** [comment]
I don't see this error. How did you install rhasspy-nlu?

**Comment by gericho** [comment]
My setup using these
https://rhasspy.readthedocs.io/en/latest/installation/

In a Virtual Environment on Raspbian Buster, rapberry pi3 mod A

**Comment by koenvervloesem** [comment]
Ok, so one of the other dependencies of rhasspy apparently needs networkx 2.4 while rhasspy-nlu has defined 2.3 in its requirements.

@synesthesiam is it safe to bump networkx 2.4 in rhasspy-nlu's dependencies?

**Comment by synesthesiam** [comment]
Yep, should be no problem to bump to 2.4.

**Comment by koenvervloesem** [comment]
Fixed in source, but rhasspy-nlu needs a new packaged version on PyPI to have this error disappear while installing Rhasspy.
